engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 40
        php:
          mass_threshold: 75
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
  scss-lint:
    enabled: true
    checks:
      Indentation:
        enabled: false

ratings:
  paths:
    - "**.css"
    - "**.php"
    - "**.scss"