env:
  global:
    - CC_TEST_REPORTER_ID=e45150bc572ac09dcd76b61600910f2f15051937124ba4931d25d6686fb33bec

language: php

php:
  - 7.2

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - cp ./nova/travis/env.travis ./.env
  - php artisan key:generate --ansi

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nova/vendor/bin/phpunit
  - nova/vendor/bin/phpcs

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT