blank_issues_enabled: false
contact_links:
    - name: Ask a Question
      url: https://github.com/anodyne/nova3/discussions?discussions_q=category%3AQ%26A
      about: Ask the community for help
    - name: Feature Request
      url: https://github.com/anodyne/nova3/discussions?discussions_q=category%3AIdeas
      about: Share ideas for new features
    - name: Bug Report
      url: https://github.com/anodyne/nova3/issues/new
      about: Report a reproducable bug
